/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AthleteRouteImport } from './routes/athlete'
import { Route as AthleteLoginRouteImport } from './routes/athlete-login'
import { Route as AthletePinSetupRouteImport } from './routes/athlete-pin-setup'
import { Route as AthleteQrRouteImport } from './routes/athlete-qr'
import { Route as AthletesRouteImport } from './routes/athletes'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard-settings'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as GpsRouteImport } from './routes/gps'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as LiftsRouteImport } from './routes/lifts'
import { Route as LiveLeaderboardRouteImport } from './routes/live-leaderboard'
import { Route as LogReviewRouteImport } from './routes/log-review'
import { Route as MaxesRouteImport } from './routes/maxes'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as OrgMembersRouteImport } from './routes/org-members'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as OverheadDisplayRouteImport } from './routes/overhead-display'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProgramDeliveryRouteImport } from './routes/program-delivery'
import { Route as ProgrammingRouteImport } from './routes/programming'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as RackConsoleRouteImport } from './routes/rack-console'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as AthleteJoinTokenRouteImport } from './routes/athlete-join.$token'
import { Route as AthleteTodayRouteImport } from './routes/athlete.today'
import { Route as AthletesIdRouteImport } from './routes/athletes.$id'
import { Route as CheckinTokenRouteImport } from './routes/checkin.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as ProgramsIdRouteImport } from './routes/programs.$id'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsGpsReportRouteImport } from './routes/reports.gps-report'
import { Route as ReportsKpiReportRouteImport } from './routes/reports.kpi-report'
import { Route as ReportsSpeedPotentialRouteImport } from './routes/reports.speed-potential'
import { Route as TrainingViewAttendanceRouteImport } from './routes/training-view.attendance'
import { Route as TrainingViewCheckInRouteImport } from './routes/training-view.check-in'
import { Route as TrainingViewSessionRouteImport } from './routes/training-view.session'
import { Route as TrainingIndexRouteImport } from './routes/training.index'
import { Route as TrainingAnalyticsRouteImport } from './routes/training.analytics'
import { Route as TrainingAssignedRouteImport } from './routes/training.assigned'
import { Route as TrainingCalendarRouteImport } from './routes/training.calendar'
import { Route as TrainingCompletedRouteImport } from './routes/training.completed'
import { Route as TrainingLiveRouteImport } from './routes/training.live'
import { Route as TrainingTodayRouteImport } from './routes/training.today'
import { Route as WorkoutsIdRouteImport } from './routes/workouts.$id'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteRoute = AthleteRouteImport.update({
  id: '/athlete',
  path: '/athlete',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteLoginRoute = AthleteLoginRouteImport.update({
  id: '/athlete-login',
  path: '/athlete-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletePinSetupRoute = AthletePinSetupRouteImport.update({
  id: '/athlete-pin-setup',
  path: '/athlete-pin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteQrRoute = AthleteQrRouteImport.update({
  id: '/athlete-qr',
  path: '/athlete-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesRoute = AthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard-settings',
  path: '/dashboard-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const GpsRoute = GpsRouteImport.update({
  id: '/gps',
  path: '/gps',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const LiftsRoute = LiftsRouteImport.update({
  id: '/lifts',
  path: '/lifts',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveLeaderboardRoute = LiveLeaderboardRouteImport.update({
  id: '/live-leaderboard',
  path: '/live-leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LogReviewRoute = LogReviewRouteImport.update({
  id: '/log-review',
  path: '/log-review',
  getParentRoute: () => rootRouteImport,
} as any)
const MaxesRoute = MaxesRouteImport.update({
  id: '/maxes',
  path: '/maxes',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgMembersRoute = OrgMembersRouteImport.update({
  id: '/org-members',
  path: '/org-members',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const OverheadDisplayRoute = OverheadDisplayRouteImport.update({
  id: '/overhead-display',
  path: '/overhead-display',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramDeliveryRoute = ProgramDeliveryRouteImport.update({
  id: '/program-delivery',
  path: '/program-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammingRoute = ProgrammingRouteImport.update({
  id: '/programming',
  path: '/programming',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const RackConsoleRoute = RackConsoleRouteImport.update({
  id: '/rack-console',
  path: '/rack-console',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteJoinTokenRoute = AthleteJoinTokenRouteImport.update({
  id: '/athlete-join/$token',
  path: '/athlete-join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteTodayRoute = AthleteTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AthleteRoute,
} as any)
const AthletesIdRoute = AthletesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AthletesRoute,
} as any)
const CheckinTokenRoute = CheckinTokenRouteImport.update({
  id: '/checkin/$token',
  path: '/checkin/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIdRoute = ProgramsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProgramsRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsGpsReportRoute = ReportsGpsReportRouteImport.update({
  id: '/gps-report',
  path: '/gps-report',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsKpiReportRoute = ReportsKpiReportRouteImport.update({
  id: '/kpi-report',
  path: '/kpi-report',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsSpeedPotentialRoute = ReportsSpeedPotentialRouteImport.update({
  id: '/speed-potential',
  path: '/speed-potential',
  getParentRoute: () => ReportsRoute,
} as any)
const TrainingViewAttendanceRoute = TrainingViewAttendanceRouteImport.update({
  id: '/training-view/attendance',
  path: '/training-view/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingViewCheckInRoute = TrainingViewCheckInRouteImport.update({
  id: '/training-view/check-in',
  path: '/training-view/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingViewSessionRoute = TrainingViewSessionRouteImport.update({
  id: '/training-view/session',
  path: '/training-view/session',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingAnalyticsRoute = TrainingAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingAssignedRoute = TrainingAssignedRouteImport.update({
  id: '/assigned',
  path: '/assigned',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingCalendarRoute = TrainingCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingCompletedRoute = TrainingCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingLiveRoute = TrainingLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingTodayRoute = TrainingTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => TrainingRoute,
} as any)
const WorkoutsIdRoute = WorkoutsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkoutsRoute,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/athlete': typeof AthleteRouteWithChildren
  '/athlete-login': typeof AthleteLoginRoute
  '/athlete-pin-setup': typeof AthletePinSetupRoute
  '/athlete-qr': typeof AthleteQrRoute
  '/athletes': typeof AthletesRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRoute
  '/dashboard-settings': typeof DashboardSettingsRoute
  '/exercises': typeof ExercisesRoute
  '/features': typeof FeaturesRoute
  '/gps': typeof GpsRoute
  '/import': typeof ImportRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/lifts': typeof LiftsRoute
  '/live-leaderboard': typeof LiveLeaderboardRoute
  '/log-review': typeof LogReviewRoute
  '/maxes': typeof MaxesRoute
  '/metrics': typeof MetricsRoute
  '/org-members': typeof OrgMembersRoute
  '/organizations': typeof OrganizationsRoute
  '/overhead-display': typeof OverheadDisplayRoute
  '/performance': typeof PerformanceRoute
  '/permissions': typeof PermissionsRoute
  '/pricing': typeof PricingRoute
  '/program-delivery': typeof ProgramDeliveryRoute
  '/programming': typeof ProgrammingRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/rack-console': typeof RackConsoleRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teams': typeof TeamsRoute
  '/tests': typeof TestsRoute
  '/training': typeof TrainingRouteWithChildren
  '/workouts': typeof WorkoutsRouteWithChildren
  '/athlete-join/$token': typeof AthleteJoinTokenRoute
  '/athlete/today': typeof AthleteTodayRoute
  '/athletes/$id': typeof AthletesIdRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/reports/gps-report': typeof ReportsGpsReportRoute
  '/reports/kpi-report': typeof ReportsKpiReportRoute
  '/reports/speed-potential': typeof ReportsSpeedPotentialRoute
  '/training-view/attendance': typeof TrainingViewAttendanceRoute
  '/training-view/check-in': typeof TrainingViewCheckInRoute
  '/training-view/session': typeof TrainingViewSessionRoute
  '/training/analytics': typeof TrainingAnalyticsRoute
  '/training/assigned': typeof TrainingAssignedRoute
  '/training/calendar': typeof TrainingCalendarRoute
  '/training/completed': typeof TrainingCompletedRoute
  '/training/live': typeof TrainingLiveRoute
  '/training/today': typeof TrainingTodayRoute
  '/workouts/$id': typeof WorkoutsIdRoute
  '/reports/': typeof ReportsIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/athlete': typeof AthleteRouteWithChildren
  '/athlete-login': typeof AthleteLoginRoute
  '/athlete-pin-setup': typeof AthletePinSetupRoute
  '/athlete-qr': typeof AthleteQrRoute
  '/athletes': typeof AthletesRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRoute
  '/dashboard-settings': typeof DashboardSettingsRoute
  '/exercises': typeof ExercisesRoute
  '/features': typeof FeaturesRoute
  '/gps': typeof GpsRoute
  '/import': typeof ImportRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/lifts': typeof LiftsRoute
  '/live-leaderboard': typeof LiveLeaderboardRoute
  '/log-review': typeof LogReviewRoute
  '/maxes': typeof MaxesRoute
  '/metrics': typeof MetricsRoute
  '/org-members': typeof OrgMembersRoute
  '/organizations': typeof OrganizationsRoute
  '/overhead-display': typeof OverheadDisplayRoute
  '/performance': typeof PerformanceRoute
  '/permissions': typeof PermissionsRoute
  '/pricing': typeof PricingRoute
  '/program-delivery': typeof ProgramDeliveryRoute
  '/programming': typeof ProgrammingRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/rack-console': typeof RackConsoleRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teams': typeof TeamsRoute
  '/tests': typeof TestsRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/athlete-join/$token': typeof AthleteJoinTokenRoute
  '/athlete/today': typeof AthleteTodayRoute
  '/athletes/$id': typeof AthletesIdRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/reports/gps-report': typeof ReportsGpsReportRoute
  '/reports/kpi-report': typeof ReportsKpiReportRoute
  '/reports/speed-potential': typeof ReportsSpeedPotentialRoute
  '/training-view/attendance': typeof TrainingViewAttendanceRoute
  '/training-view/check-in': typeof TrainingViewCheckInRoute
  '/training-view/session': typeof TrainingViewSessionRoute
  '/training/analytics': typeof TrainingAnalyticsRoute
  '/training/assigned': typeof TrainingAssignedRoute
  '/training/calendar': typeof TrainingCalendarRoute
  '/training/completed': typeof TrainingCompletedRoute
  '/training/live': typeof TrainingLiveRoute
  '/training/today': typeof TrainingTodayRoute
  '/workouts/$id': typeof WorkoutsIdRoute
  '/reports': typeof ReportsIndexRoute
  '/training': typeof TrainingIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/athlete': typeof AthleteRouteWithChildren
  '/athlete-login': typeof AthleteLoginRoute
  '/athlete-pin-setup': typeof AthletePinSetupRoute
  '/athlete-qr': typeof AthleteQrRoute
  '/athletes': typeof AthletesRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRoute
  '/dashboard-settings': typeof DashboardSettingsRoute
  '/exercises': typeof ExercisesRoute
  '/features': typeof FeaturesRoute
  '/gps': typeof GpsRoute
  '/import': typeof ImportRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/lifts': typeof LiftsRoute
  '/live-leaderboard': typeof LiveLeaderboardRoute
  '/log-review': typeof LogReviewRoute
  '/maxes': typeof MaxesRoute
  '/metrics': typeof MetricsRoute
  '/org-members': typeof OrgMembersRoute
  '/organizations': typeof OrganizationsRoute
  '/overhead-display': typeof OverheadDisplayRoute
  '/performance': typeof PerformanceRoute
  '/permissions': typeof PermissionsRoute
  '/pricing': typeof PricingRoute
  '/program-delivery': typeof ProgramDeliveryRoute
  '/programming': typeof ProgrammingRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/rack-console': typeof RackConsoleRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teams': typeof TeamsRoute
  '/tests': typeof TestsRoute
  '/training': typeof TrainingRouteWithChildren
  '/workouts': typeof WorkoutsRouteWithChildren
  '/athlete-join/$token': typeof AthleteJoinTokenRoute
  '/athlete/today': typeof AthleteTodayRoute
  '/athletes/$id': typeof AthletesIdRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/reports/gps-report': typeof ReportsGpsReportRoute
  '/reports/kpi-report': typeof ReportsKpiReportRoute
  '/reports/speed-potential': typeof ReportsSpeedPotentialRoute
  '/training-view/attendance': typeof TrainingViewAttendanceRoute
  '/training-view/check-in': typeof TrainingViewCheckInRoute
  '/training-view/session': typeof TrainingViewSessionRoute
  '/training/analytics': typeof TrainingAnalyticsRoute
  '/training/assigned': typeof TrainingAssignedRoute
  '/training/calendar': typeof TrainingCalendarRoute
  '/training/completed': typeof TrainingCompletedRoute
  '/training/live': typeof TrainingLiveRoute
  '/training/today': typeof TrainingTodayRoute
  '/workouts/$id': typeof WorkoutsIdRoute
  '/reports/': typeof ReportsIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/athlete'
    | '/athlete-login'
    | '/athlete-pin-setup'
    | '/athlete-qr'
    | '/athletes'
    | '/attendance'
    | '/auth'
    | '/badges'
    | '/dashboard-settings'
    | '/exercises'
    | '/features'
    | '/gps'
    | '/import'
    | '/leaderboards'
    | '/lifts'
    | '/live-leaderboard'
    | '/log-review'
    | '/maxes'
    | '/metrics'
    | '/org-members'
    | '/organizations'
    | '/overhead-display'
    | '/performance'
    | '/permissions'
    | '/pricing'
    | '/program-delivery'
    | '/programming'
    | '/programs'
    | '/rack-console'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/setup'
    | '/sitemap.xml'
    | '/teams'
    | '/tests'
    | '/training'
    | '/workouts'
    | '/athlete-join/$token'
    | '/athlete/today'
    | '/athletes/$id'
    | '/checkin/$token'
    | '/invite/$token'
    | '/join/$token'
    | '/programs/$id'
    | '/reports/gps-report'
    | '/reports/kpi-report'
    | '/reports/speed-potential'
    | '/training-view/attendance'
    | '/training-view/check-in'
    | '/training-view/session'
    | '/training/analytics'
    | '/training/assigned'
    | '/training/calendar'
    | '/training/completed'
    | '/training/live'
    | '/training/today'
    | '/workouts/$id'
    | '/reports/'
    | '/training/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/athlete'
    | '/athlete-login'
    | '/athlete-pin-setup'
    | '/athlete-qr'
    | '/athletes'
    | '/attendance'
    | '/auth'
    | '/badges'
    | '/dashboard-settings'
    | '/exercises'
    | '/features'
    | '/gps'
    | '/import'
    | '/leaderboards'
    | '/lifts'
    | '/live-leaderboard'
    | '/log-review'
    | '/maxes'
    | '/metrics'
    | '/org-members'
    | '/organizations'
    | '/overhead-display'
    | '/performance'
    | '/permissions'
    | '/pricing'
    | '/program-delivery'
    | '/programming'
    | '/programs'
    | '/rack-console'
    | '/reset-password'
    | '/settings'
    | '/setup'
    | '/sitemap.xml'
    | '/teams'
    | '/tests'
    | '/workouts'
    | '/athlete-join/$token'
    | '/athlete/today'
    | '/athletes/$id'
    | '/checkin/$token'
    | '/invite/$token'
    | '/join/$token'
    | '/programs/$id'
    | '/reports/gps-report'
    | '/reports/kpi-report'
    | '/reports/speed-potential'
    | '/training-view/attendance'
    | '/training-view/check-in'
    | '/training-view/session'
    | '/training/analytics'
    | '/training/assigned'
    | '/training/calendar'
    | '/training/completed'
    | '/training/live'
    | '/training/today'
    | '/workouts/$id'
    | '/reports'
    | '/training'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/athlete'
    | '/athlete-login'
    | '/athlete-pin-setup'
    | '/athlete-qr'
    | '/athletes'
    | '/attendance'
    | '/auth'
    | '/badges'
    | '/dashboard-settings'
    | '/exercises'
    | '/features'
    | '/gps'
    | '/import'
    | '/leaderboards'
    | '/lifts'
    | '/live-leaderboard'
    | '/log-review'
    | '/maxes'
    | '/metrics'
    | '/org-members'
    | '/organizations'
    | '/overhead-display'
    | '/performance'
    | '/permissions'
    | '/pricing'
    | '/program-delivery'
    | '/programming'
    | '/programs'
    | '/rack-console'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/setup'
    | '/sitemap.xml'
    | '/teams'
    | '/tests'
    | '/training'
    | '/workouts'
    | '/athlete-join/$token'
    | '/athlete/today'
    | '/athletes/$id'
    | '/checkin/$token'
    | '/invite/$token'
    | '/join/$token'
    | '/programs/$id'
    | '/reports/gps-report'
    | '/reports/kpi-report'
    | '/reports/speed-potential'
    | '/training-view/attendance'
    | '/training-view/check-in'
    | '/training-view/session'
    | '/training/analytics'
    | '/training/assigned'
    | '/training/calendar'
    | '/training/completed'
    | '/training/live'
    | '/training/today'
    | '/workouts/$id'
    | '/reports/'
    | '/training/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AthleteRoute: typeof AthleteRouteWithChildren
  AthleteLoginRoute: typeof AthleteLoginRoute
  AthletePinSetupRoute: typeof AthletePinSetupRoute
  AthleteQrRoute: typeof AthleteQrRoute
  AthletesRoute: typeof AthletesRouteWithChildren
  AttendanceRoute: typeof AttendanceRoute
  AuthRoute: typeof AuthRoute
  BadgesRoute: typeof BadgesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  ExercisesRoute: typeof ExercisesRoute
  FeaturesRoute: typeof FeaturesRoute
  GpsRoute: typeof GpsRoute
  ImportRoute: typeof ImportRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  LiftsRoute: typeof LiftsRoute
  LiveLeaderboardRoute: typeof LiveLeaderboardRoute
  LogReviewRoute: typeof LogReviewRoute
  MaxesRoute: typeof MaxesRoute
  MetricsRoute: typeof MetricsRoute
  OrgMembersRoute: typeof OrgMembersRoute
  OrganizationsRoute: typeof OrganizationsRoute
  OverheadDisplayRoute: typeof OverheadDisplayRoute
  PerformanceRoute: typeof PerformanceRoute
  PermissionsRoute: typeof PermissionsRoute
  PricingRoute: typeof PricingRoute
  ProgramDeliveryRoute: typeof ProgramDeliveryRoute
  ProgrammingRoute: typeof ProgrammingRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  RackConsoleRoute: typeof RackConsoleRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamsRoute: typeof TeamsRoute
  TestsRoute: typeof TestsRoute
  TrainingRoute: typeof TrainingRouteWithChildren
  WorkoutsRoute: typeof WorkoutsRouteWithChildren
  AthleteJoinTokenRoute: typeof AthleteJoinTokenRoute
  CheckinTokenRoute: typeof CheckinTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
  JoinTokenRoute: typeof JoinTokenRoute
  TrainingViewAttendanceRoute: typeof TrainingViewAttendanceRoute
  TrainingViewCheckInRoute: typeof TrainingViewCheckInRoute
  TrainingViewSessionRoute: typeof TrainingViewSessionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete': {
      id: '/athlete'
      path: '/athlete'
      fullPath: '/athlete'
      preLoaderRoute: typeof AthleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete-login': {
      id: '/athlete-login'
      path: '/athlete-login'
      fullPath: '/athlete-login'
      preLoaderRoute: typeof AthleteLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete-pin-setup': {
      id: '/athlete-pin-setup'
      path: '/athlete-pin-setup'
      fullPath: '/athlete-pin-setup'
      preLoaderRoute: typeof AthletePinSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete-qr': {
      id: '/athlete-qr'
      path: '/athlete-qr'
      fullPath: '/athlete-qr'
      preLoaderRoute: typeof AthleteQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes': {
      id: '/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-settings': {
      id: '/dashboard-settings'
      path: '/dashboard-settings'
      fullPath: '/dashboard-settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gps': {
      id: '/gps'
      path: '/gps'
      fullPath: '/gps'
      preLoaderRoute: typeof GpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifts': {
      id: '/lifts'
      path: '/lifts'
      fullPath: '/lifts'
      preLoaderRoute: typeof LiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-leaderboard': {
      id: '/live-leaderboard'
      path: '/live-leaderboard'
      fullPath: '/live-leaderboard'
      preLoaderRoute: typeof LiveLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-review': {
      id: '/log-review'
      path: '/log-review'
      fullPath: '/log-review'
      preLoaderRoute: typeof LogReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maxes': {
      id: '/maxes'
      path: '/maxes'
      fullPath: '/maxes'
      preLoaderRoute: typeof MaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org-members': {
      id: '/org-members'
      path: '/org-members'
      fullPath: '/org-members'
      preLoaderRoute: typeof OrgMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overhead-display': {
      id: '/overhead-display'
      path: '/overhead-display'
      fullPath: '/overhead-display'
      preLoaderRoute: typeof OverheadDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-delivery': {
      id: '/program-delivery'
      path: '/program-delivery'
      fullPath: '/program-delivery'
      preLoaderRoute: typeof ProgramDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programming': {
      id: '/programming'
      path: '/programming'
      fullPath: '/programming'
      preLoaderRoute: typeof ProgrammingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rack-console': {
      id: '/rack-console'
      path: '/rack-console'
      fullPath: '/rack-console'
      preLoaderRoute: typeof RackConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete-join/$token': {
      id: '/athlete-join/$token'
      path: '/athlete-join/$token'
      fullPath: '/athlete-join/$token'
      preLoaderRoute: typeof AthleteJoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/today': {
      id: '/athlete/today'
      path: '/today'
      fullPath: '/athlete/today'
      preLoaderRoute: typeof AthleteTodayRouteImport
      parentRoute: typeof AthleteRoute
    }
    '/athletes/$id': {
      id: '/athletes/$id'
      path: '/$id'
      fullPath: '/athletes/$id'
      preLoaderRoute: typeof AthletesIdRouteImport
      parentRoute: typeof AthletesRoute
    }
    '/checkin/$token': {
      id: '/checkin/$token'
      path: '/checkin/$token'
      fullPath: '/checkin/$token'
      preLoaderRoute: typeof CheckinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$id': {
      id: '/programs/$id'
      path: '/$id'
      fullPath: '/programs/$id'
      preLoaderRoute: typeof ProgramsIdRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/gps-report': {
      id: '/reports/gps-report'
      path: '/gps-report'
      fullPath: '/reports/gps-report'
      preLoaderRoute: typeof ReportsGpsReportRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/kpi-report': {
      id: '/reports/kpi-report'
      path: '/kpi-report'
      fullPath: '/reports/kpi-report'
      preLoaderRoute: typeof ReportsKpiReportRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/speed-potential': {
      id: '/reports/speed-potential'
      path: '/speed-potential'
      fullPath: '/reports/speed-potential'
      preLoaderRoute: typeof ReportsSpeedPotentialRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/training-view/attendance': {
      id: '/training-view/attendance'
      path: '/training-view/attendance'
      fullPath: '/training-view/attendance'
      preLoaderRoute: typeof TrainingViewAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-view/check-in': {
      id: '/training-view/check-in'
      path: '/training-view/check-in'
      fullPath: '/training-view/check-in'
      preLoaderRoute: typeof TrainingViewCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-view/session': {
      id: '/training-view/session'
      path: '/training-view/session'
      fullPath: '/training-view/session'
      preLoaderRoute: typeof TrainingViewSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/analytics': {
      id: '/training/analytics'
      path: '/analytics'
      fullPath: '/training/analytics'
      preLoaderRoute: typeof TrainingAnalyticsRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/assigned': {
      id: '/training/assigned'
      path: '/assigned'
      fullPath: '/training/assigned'
      preLoaderRoute: typeof TrainingAssignedRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/calendar': {
      id: '/training/calendar'
      path: '/calendar'
      fullPath: '/training/calendar'
      preLoaderRoute: typeof TrainingCalendarRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/completed': {
      id: '/training/completed'
      path: '/completed'
      fullPath: '/training/completed'
      preLoaderRoute: typeof TrainingCompletedRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/live': {
      id: '/training/live'
      path: '/live'
      fullPath: '/training/live'
      preLoaderRoute: typeof TrainingLiveRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/today': {
      id: '/training/today'
      path: '/today'
      fullPath: '/training/today'
      preLoaderRoute: typeof TrainingTodayRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/workouts/$id': {
      id: '/workouts/$id'
      path: '/$id'
      fullPath: '/workouts/$id'
      preLoaderRoute: typeof WorkoutsIdRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AthleteRouteChildren {
  AthleteTodayRoute: typeof AthleteTodayRoute
}

const AthleteRouteChildren: AthleteRouteChildren = {
  AthleteTodayRoute: AthleteTodayRoute,
}

const AthleteRouteWithChildren =
  AthleteRoute._addFileChildren(AthleteRouteChildren)

interface AthletesRouteChildren {
  AthletesIdRoute: typeof AthletesIdRoute
}

const AthletesRouteChildren: AthletesRouteChildren = {
  AthletesIdRoute: AthletesIdRoute,
}

const AthletesRouteWithChildren = AthletesRoute._addFileChildren(
  AthletesRouteChildren,
)

interface ProgramsRouteChildren {
  ProgramsIdRoute: typeof ProgramsIdRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsIdRoute: ProgramsIdRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

interface ReportsRouteChildren {
  ReportsGpsReportRoute: typeof ReportsGpsReportRoute
  ReportsKpiReportRoute: typeof ReportsKpiReportRoute
  ReportsSpeedPotentialRoute: typeof ReportsSpeedPotentialRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsGpsReportRoute: ReportsGpsReportRoute,
  ReportsKpiReportRoute: ReportsKpiReportRoute,
  ReportsSpeedPotentialRoute: ReportsSpeedPotentialRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface TrainingRouteChildren {
  TrainingAnalyticsRoute: typeof TrainingAnalyticsRoute
  TrainingAssignedRoute: typeof TrainingAssignedRoute
  TrainingCalendarRoute: typeof TrainingCalendarRoute
  TrainingCompletedRoute: typeof TrainingCompletedRoute
  TrainingLiveRoute: typeof TrainingLiveRoute
  TrainingTodayRoute: typeof TrainingTodayRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
}

const TrainingRouteChildren: TrainingRouteChildren = {
  TrainingAnalyticsRoute: TrainingAnalyticsRoute,
  TrainingAssignedRoute: TrainingAssignedRoute,
  TrainingCalendarRoute: TrainingCalendarRoute,
  TrainingCompletedRoute: TrainingCompletedRoute,
  TrainingLiveRoute: TrainingLiveRoute,
  TrainingTodayRoute: TrainingTodayRoute,
  TrainingIndexRoute: TrainingIndexRoute,
}

const TrainingRouteWithChildren = TrainingRoute._addFileChildren(
  TrainingRouteChildren,
)

interface WorkoutsRouteChildren {
  WorkoutsIdRoute: typeof WorkoutsIdRoute
}

const WorkoutsRouteChildren: WorkoutsRouteChildren = {
  WorkoutsIdRoute: WorkoutsIdRoute,
}

const WorkoutsRouteWithChildren = WorkoutsRoute._addFileChildren(
  WorkoutsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AthleteRoute: AthleteRouteWithChildren,
  AthleteLoginRoute: AthleteLoginRoute,
  AthletePinSetupRoute: AthletePinSetupRoute,
  AthleteQrRoute: AthleteQrRoute,
  AthletesRoute: AthletesRouteWithChildren,
  AttendanceRoute: AttendanceRoute,
  AuthRoute: AuthRoute,
  BadgesRoute: BadgesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  ExercisesRoute: ExercisesRoute,
  FeaturesRoute: FeaturesRoute,
  GpsRoute: GpsRoute,
  ImportRoute: ImportRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  LiftsRoute: LiftsRoute,
  LiveLeaderboardRoute: LiveLeaderboardRoute,
  LogReviewRoute: LogReviewRoute,
  MaxesRoute: MaxesRoute,
  MetricsRoute: MetricsRoute,
  OrgMembersRoute: OrgMembersRoute,
  OrganizationsRoute: OrganizationsRoute,
  OverheadDisplayRoute: OverheadDisplayRoute,
  PerformanceRoute: PerformanceRoute,
  PermissionsRoute: PermissionsRoute,
  PricingRoute: PricingRoute,
  ProgramDeliveryRoute: ProgramDeliveryRoute,
  ProgrammingRoute: ProgrammingRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  RackConsoleRoute: RackConsoleRoute,
  ReportsRoute: ReportsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamsRoute: TeamsRoute,
  TestsRoute: TestsRoute,
  TrainingRoute: TrainingRouteWithChildren,
  WorkoutsRoute: WorkoutsRouteWithChildren,
  AthleteJoinTokenRoute: AthleteJoinTokenRoute,
  CheckinTokenRoute: CheckinTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
  JoinTokenRoute: JoinTokenRoute,
  TrainingViewAttendanceRoute: TrainingViewAttendanceRoute,
  TrainingViewCheckInRoute: TrainingViewCheckInRoute,
  TrainingViewSessionRoute: TrainingViewSessionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
